---
- hosts: localhost
  gather_facts: false
  vars_files:
    - vars.yaml

  tasks:
    - name: Provision instance
      ec2:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        key_name: aws_key
        instance_type: t2.micro
        image: ami-0d1cd67c26f5fca19
        wait: yes
        region: us-west-2
        # Begin
        # These line make sure we do not keep launching
        # new instances everythime this play book is run.
        # A poor man's idempotency.
        instance_tags:
          Name: launch_by_ansible
        exact_count: 0
        count_tag:
          Name: launch_by_ansible
        # End
