---
- name: Make files
  hosts: localhost
  gather_facts: False
  vars:
    start: 1
    end: 4

  tasks:
  - name: Set word
    shell: |
      grep {{ item }} datafile.txt | cut -d ' ' -f2
    register: word_var
    loop: "{{ range(start, end) | list }}"

  - name: Set letter
    shell: |
      grep {{ item }} datafile.txt | cut -d ' ' -f3
    register: letter_var
    loop: "{{ range(start, end) | list }}"

  - name: with_together -> loop
    ansible.builtin.debug:
      msg: "{{ item.0.stdout }} - {{ item.1.stdout }}"
    loop: "{{ word_var.results|zip(letter_var.results)|list }}"


  - name: create files
    template:
      src: template-file.j2
      dest: "{{ item.0.stdout }}_file.txt"
    loop: "{{ word_var.results|zip(letter_var.results)|list }}"


# - name: with_together -> loop
#   ansible.builtin.debug:
#     msg: "{{ item.0 }} - {{ item.1 }}"
#   loop: "{{ list_one|zip(list_two)|list }}"
